# Generated by Django 3.1.2 on 2020-10-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20201003_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='stat',
            field=models.CharField(choices=[('NW', 'New'), ('PL', 'Planned'), ('IH', 'In hand'), ('CL', 'Completed')], default='NW', max_length=2),
        ),
    ]
