# Generated by Django 3.1.2 on 2020-10-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_planned',
            field=models.DateTimeField(null=True),
        ),
    ]
