# Generated by Django 3.1.2 on 2020-10-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_date_planned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='stat',
            field=models.CharField(choices=[('New', 'New'), ('PL', 'Planned'), ('IH', 'In hand'), ('CL', 'Completed')], default='NW', max_length=10),
        ),
    ]
