# Generated by Django 3.1.2 on 2020-10-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20201005_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_planned',
            field=models.DateTimeField(null=True, verbose_name='YYYY-MM-DD HH-MM-SS'),
        ),
    ]
